-- 6. App Config and Admin Management
-- Created at: 2026-04-25

create table public.app_admin_members (
  id bigint generated by default as identity primary key,
  user_id text unique,
  email text unique,
  added_by_user_id text,
  added_by_email text,
  created_at timestamptz not null default now()
);

create table public.app_config (
  id boolean primary key default true,
  app_name text not null default 'LMS',
  course_creation_mode text not null default 'app_admin' check (course_creation_mode in ('app_admin', 'org_staff')),
  bunny_storage_zone text,
  bunny_storage_access_key text,
  bunny_storage_cdn_url text,
  bunny_storage_region text default 'ny',
  support_email text default '',
  brand_color text default '#4f46e5',
  custom_head_scripts text default '',
  stripe_public_key text default '',
  stripe_secret_key text default '',
  stripe_webhook_secret text default '',
  updated_at timestamptz,
  constraint single_row check (id = true)
);

-- RLS Policies
alter table public.app_admin_members enable row level security;
alter table public.app_config enable row level security;

-- Admin Members
create policy "Admin select" on public.app_admin_members for select using (public.get_my_role() = 'admin');

-- App Config
create policy "Config select" on public.app_config for select using (true);
create policy "Config update" on public.app_config for update using (public.get_my_role() = 'admin');
