create table if not exists public.app_admin_members (
  id bigint generated by default as identity primary key,
  user_id text,
  email text,
  added_by_user_id text,
  added_by_email text,
  created_at timestamptz not null default now(),
  constraint app_admin_members_identity_check check (user_id is not null or email is not null)
);

create unique index if not exists app_admin_members_user_id_unique
  on public.app_admin_members (user_id)
  where user_id is not null;

create unique index if not exists app_admin_members_email_unique
  on public.app_admin_members (email)
  where email is not null;

alter table public.app_admin_members enable row level security;
